#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/DeltaNotchCC3D.sh -t deltanotchcc3d \
                         -u compucell3d-4.2.2 \
                         -w captive \
                         -r none
