#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/DeltaNotchCC3D.sh -t deltanotchcc3d \
                         -u compucell3d-4.1.1 \
                         -w captive \
                         -r none
